config/routes.rb
Rails.application.routes.draw do
  resources :inscricaos
  root 'inscricaos#new'
    get '/email', to: 'inscricaos#email'
    get '/telemovel', to: 'inscricaos#telemoveis'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inscricao.rb
class Inscricao < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inscricaos_controller.rb
class InscricaosController < ApplicationController
  before_action :set_inscricao, only: [:show, :edit, :update, :destroy]

  # GET /inscricaos
  # GET /inscricaos.json
  def index
    @inscricaos = Inscricao.order(:id)
  end

  def email
    @inscricaos = Inscricao.order(:id)
  end

  def telemoveis
    @inscricaos = Inscricao.order(:id)
  end
  # GET /inscricaos/1
  # GET /inscricaos/1.json
  def show
  end

  # GET /inscricaos/new
  def new
    @inscricao = Inscricao.new
  end

  # GET /inscricaos/1/edit
  def edit
  end

  # POST /inscricaos
  # POST /inscricaos.json
  def create
    @inscricao = Inscricao.new(inscricao_params)
    
    respond_to do |format|
      if @inscricao.save
        InscricaoMailer.confirmacao_inscricao(@inscricao).deliver
        format.html { redirect_to @inscricao, notice: 'A sua inscrição foi submetida com sucesso irá receber um link para pagamento em menos de 24 horas' }
        format.json { render :show, status: :created, location: @inscricao }
      else
        format.html { render :new }
        format.json { render json: @inscricao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscricaos/1
  # PATCH/PUT /inscricaos/1.json
  def update
    respond_to do |format|
      if @inscricao.update(inscricao_params)
        format.html { redirect_to @inscricao, notice: 'Inscrição Validada.' }
        format.json { render :show, status: :ok, location: @inscricao }
      else
        format.html { render :edit }
        format.json { render json: @inscricao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscricaos/1
  # DELETE /inscricaos/1.json
  def destroy
    @inscricao.destroy
    respond_to do |format|
      format.html { redirect_to inscricaos_url, notice: 'Inscricao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscricao
      @inscricao = Inscricao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inscricao_params
      params.require(:inscricao).permit(:nome, :telefone, :email, :tipo, :categoria, :municipio, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inscricaos_helper.rb
module InscricaosHelper
end

app/views/inscricaos/_form.html.erb
<%= form_with(model: inscricao, local: true) do |form| %>
  <% if inscricao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inscricao.errors.count, "error") %> prohibited this inscricao from being saved:</h2>

      <ul>
        <% inscricao.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row ">
    <div class="name">Nome</div>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :nome, class:'input--style-5'%>
      </div>
    </div>
  </div>

  <div class="form-row ">
    <div class="name">Telemóvel</div>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :telefone,class:'input--style-5'   %>
      </div>
    </div>
  </div>

  <div class="form-row ">
    <div class="name">Email</div>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :email,class:'input--style-5' %>
      </div>
    </div>
  </div>

  <div class="form-row ">
    <div class="name">Tipo</div>
    <div class="value">
      <div class="input-group">
        <div class="field">
          <%= form.select :tipo, ['PAM', 'Substituto', 'Outros'] %>
        </div>
      </div>
    </div>


    <div class="form-row ">
      <div class="name">Categoria</div>
      <div class="value">
        <div class="input-group">
          <%= form.select :categoria, ['Delegado', 'Observador'] %>


        </div>
      </div>
    </div>
  </div>
  <div class="form-row ">
    <div class="name">Município</div>
    <div class="value">
      <div class="input-group">
        <%= form.text_field :municipio ,class:'input--style-5' %>
      </div>
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Submeter inscrição" , :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/inscricaos/edit.html.erb
<div class="wrapper wrapper--w790">
  <div class="card card-5">
    <div class="card-heading">
      <h2 class="title">Submeter comprovativo</h2>
    </div>
    <div class="card-body">
      <%= form_with(model: @inscricao, local: true) do |form| %>

        <div class="form-row ">
          <div class="name">Comprovativo <br>de pagamento</div>
          <div class="value">
            <div class="input-group">
              <%= form.file_field :image ,class:'input--style-5' %>
            </div>
          </div>
        </div>

        <br>


        <div class="actions">
          <%= form.submit "Submeter comprovativo" , :class => 'btn btn-primary' %>
        </div>

      <% end %>

    </div>
  </div>
</div>
<div class="wrapper wrapper--w790">
  <div class="card card-5">
    <div class="card-heading">
      <h2 class="title">Editar inscrito</h2>
    </div>
    <div class="card-body">
      <%= render 'form', inscricao: @inscricao %>
    </div>
  </div>
</div>
<%= link_to 'Ver', @inscricao %> |

app/views/inscricaos/email.html.erb
    <% @inscricaos.each do |inscricao| %>
      <%= inscricao.email %><br>
    <% end %>

app/views/inscricaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inscrições</h1>
<div class="table-responsive">
<table class="table table-striped w-auto">
  <thead>
    <tr>
    <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Telefone</th>
      <th scope="col">Email</th>
      <th scope="col">Tipo</th>
      <th scope="col">Categoria</th>
      <th scope="col">Municipio</th>
      <th scope="col">Opções</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% i=1 %>
  <tbody>
    <% @inscricaos.each do |inscricao| %>
      <tr>
      <th scope="row"><%= i %></th>
        <td><%= inscricao.nome %></td>
        <td><%= inscricao.telefone %></td>
        <td><%= inscricao.email %></td>
        <td><%= inscricao.tipo %></td>
        <td><%= inscricao.categoria %></td>
        <td><%= inscricao.municipio %></td>
        <td><%= link_to 'Mostrar', inscricao %></td>
        <td><%= link_to 'Editar', edit_inscricao_path(inscricao) %></td>
        <td><%= link_to 'Eliminar', inscricao, method: :delete, data: { confirm: 'Tem a certe?' } %></td>
      </tr>
      <% i+=1 %>
    <% end %>
  </tbody>
</table>
</div>
<br>
<h3>Total de Inscritos:<%=@inscricaos.count %></h3> <br>
<%= link_to 'Nova Inscricao', new_inscricao_path %>

app/views/inscricaos/new.html.erb
<div class="wrapper wrapper--w790">
            <div class="card card-5">
                <div class="card-heading">
                    <h2 class="title">Formulário de Registo</h2>
                </div>
                <div class="card-body">
<%= render 'form', inscricao: @inscricao %>
</div>
</div>
</div>

app/views/inscricaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @inscricao.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @inscricao.telefone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inscricao.email %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @inscricao.tipo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @inscricao.categoria %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @inscricao.municipio %>
</p>
<div class="container">
<div class="row">
<div class="col-md-12">
<% if @inscricao.image.attached? %>
<div class="imagem2">
<%= image_tag(@inscricao.image) %>
</div>
<%else%>
<div class="imagem"></div>

<%end%>
</div>
</div>
</div>

app/views/inscricaos/telemoveis.html.erb
    <% @inscricaos.each do |inscricao| %>
      <%= inscricao.telefone%><br>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ANAM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
 <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>